import numpy as np
import turtle
turtle.shape('turtle')
a=(1,4,1,7,0,0)
for b in a:
    if b==1:
        turtle.penup()
        turtle.right(90)
        turtle.forward(10)
        turtle.pendown()
        turtle.left(135)
        turtle.forward(np.sqrt(200))
        turtle.right(135)
        turtle.forward(20)
        turtle.penup()
        turtle.left(180)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
        turtle.pendown()
    if b==4:
        turtle.right(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.left(90)
        turtle.forward(10)
        turtle.right(180)
        turtle.forward(20)
        turtle.penup()
        turtle.left(180)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
        turtle.pendown()
    if b==7:
        turtle.forward(10)
        turtle.right(135)
        turtle.forward(np.sqrt(200))
        turtle.left(45)
        turtle.forward(10)
        turtle.penup()
        turtle.left(180)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(20)
        turtle.pendown()
    if b==0:
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(10)
        turtle.right(90)
        turtle.forward(20)
        turtle.penup()
        turtle.right(90)
        turtle.forward(20)
        turtle.pendown()
A=list(a)
